# version: '3'

# services:
#   server:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/server
#     ports:
#       - "8000:8000"
version: '3.7'

services:
  server:
    build: .
    image: gcr.io/custom-dominion-289913/test
    environment:
      PORT: 8000
    ports:
      - 8000:8000